# Kapitel 3

## Faktafrågor

1. i en regressionsproblem så är man ute efter ett kontonuerlig numeriskt värde. 

Tillämnings områden kan vara när vi har många features och vi vill få ett värde som är baserad på dessa features. till exempel hus pris beroande på olika specifikationer om huset.

2. rmse, är rutan ur av den genomstiliga värdet av summan av skillnaden mellan akta och pridikterade värdena i kvadrat.här i resultat får vi samma enhet som inmatnings data.

mse, är den genomsnitliga värdet av summan av skillnaden mellan akta och pridikterade värdena i kvadrat. Här får vi resultats enhet i kvadrat dvs, kr^2. 

mae, är den genomsnitliga värdet av summan av absolutvärdet av skillnaden mellan äkta och pridikterade värdena.

3. ja det spelar roll för att mse tar kortare tid jämfört med rmse. så om man ska bara rangordna då är bättre med mse.

4. Gradient descent betyder när modellen försöker att minska dess fel genom att göra små inre justeringar.

5. Bias variance trade-off betyder att, om vi ökar variance då minskar bias och om vi ökar bias då minskar variance alltså vi måste hitta en balance där modellen presterar som best. 

bias är när en modell förenklar för mycket. dvs underanpassar.  

variance är när en modell har för mycket detaljer. dvs överanpassar.

en modell som är komplex är inte bra för att enligt parsmony principle ska man göra saker så enklet så länge det går. till exempel en bank som anväder sig av en komplex modell kanske kommer inte kunna svara kunden varför de har tatt ett belsut för att modellen är för komplex och har bara gett ett svar som inte går att förklara.

6. linjär regression, den hittar vikter som minimerar summan av kvadratiska fel mellan predikterade och faktiska värden.

ridge, som linjär reg men använder L2-straff som kryper koefficienter för att minksa överfitting. 

lasso, som linjär reg men använder L1-straff som kan nolla koefficienter och på så sätt välja featurs. 

elastic nät, komination av ridge och lasso. den använder både L1 och L2 straff.

SVR, istället för att minimera alla fel, hittar modellen en funktion som ligger inom ett visst felmarginal kring de sanna värdena. fel inom marginalen ingoreras helt medans fel utanför straffas. 


regressionsträd, delar upp data i grenar via villkor på features tills löven ger en prediktion. 

Ensemble learning, teknik där man kombinerar flera modeller för att få bättre prediktion.


Random forest reggressor, begging med beslutsträd där varje uppdelning bara får välja bland slumpmässiga features.

7. white box, är en modell som är lätt att förstå hur den har fattat ett beslut.

black box, är en modell som är omöjligt att förstå hur den har fattat ett beslut.

8. i bagging man får använda samma datapunkt fleragånger medans i pasting får man använda en datapunkt bara en gång.

## Resonemangfrågor

9. den visar en linjär regrissonsmodel där x-axel är ålder och y-axel är inkomst. svarta punkter är sanna värde medans den blå linje är modellens prediktion. de röda linjerna är residualer alltså differansan mellan sanna och predikterade värdena.

10. den visar beslutstärds olika nivåer och hur de delar sig i grenar beroande på villkoret. 

figur 3.14 är visulaisering av figur 3.13. de tre segment är olika x värde som vi kan se i trädet. prickernas färg är det sanna värdet medans i den box de har hamat är deras predikterade värde.

11. R^2 eller determinationskoeffcienten berätter hur står andel av variation som modellen har lyckats förklara. 

1 är att gissa perfekt, 0 är som att gissa som genomsnitt, -R^2 är som att gissa sämre än genomsnitt.

## Koduppgifter

uppgift_13

In [21]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\amir_\repos\antonio\ai-python-hai25ha\.venv\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\amir_\repos\antonio\ai-python-hai25ha\.venv\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
import pandas as pd

In [23]:
df = pd.read_excel('HR_Employee_Data.xlsx')

## EDA

In [24]:
df.head(10)

,Emp_Id,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,IND02438,0.38,0.53,2,157,3,0,1,0,sales,low
1,IND28133,0.80,0.86,5,262,6,0,1,0,sales,medium
2,IND07164,0.11,0.88,7,272,4,0,1,0,sales,medium
3,IND30478,0.72,0.87,5,223,5,0,1,0,sales,low
4,IND24003,0.37,0.52,2,159,3,0,1,0,sales,low
5,IND08609,0.41,0.50,2,153,3,0,1,0,sales,low
6,IND14345,0.10,0.77,6,247,4,0,1,0,sales,low
7,IND16300,0.92,0.85,5,259,5,0,1,0,sales,low
8,IND27336,0.89,1.00,5,224,5,0,1,0,sales,low
9,IND41409,0.42,0.53,2,142,3,0,1,0,sales,low

In [25]:
df.shape

(14999, 11)

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Emp_Id                 14999 non-null  str
 1   satisfaction_level     14999 non-null  float64
 2   last_evaluation        14999 non-null  float64
 3   number_project         14999 non-null  int64
 4   average_montly_hours   14999 non-null  int64
 5   time_spend_company     14999 non-null  int64
 6   Work_accident          14999 non-null  int64
 7   left                   14999 non-null  int64
 8   promotion_last_5years  14999 non-null  int64
 9   Department             14999 non-null  str
 10  salary                 14999 non-null  str
dtypes: float64(2), int64(6), str(3)
memory usage: 1.3 MB

In [27]:
df.describe().round(2)

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years
count,14999.00,14999.00,14999.00,14999.00,14999.00,14999.00,14999.00,14999.00
mean,0.61,0.72,3.80,201.05,3.50,0.14,0.24,0.02
std,0.25,0.17,1.23,49.94,1.46,0.35,0.43,0.14
min,0.09,0.36,2.00,96.00,2.00,0.00,0.00,0.00
25%,0.44,0.56,3.00,156.00,3.00,0.00,0.00,0.00
50%,0.64,0.72,4.00,200.00,3.00,0.00,0.00,0.00
75%,0.82,0.87,5.00,245.00,4.00,0.00,0.00,0.00
max,1.00,1.00,7.00,310.00,10.00,1.00,1.00,1.00

In [28]:
df.isnull().sum()

Emp_Id                   0
satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
Department               0
salary                   0
dtype: int64

In [29]:
df.corr(numeric_only=True)['satisfaction_level'].sort_values(ascending=False)

satisfaction_level       1.000000
last_evaluation          0.105021
Work_accident            0.058697
promotion_last_5years    0.025605
average_montly_hours    -0.020048
time_spend_company      -0.100866
number_project          -0.142970
left                    -0.388375
Name: satisfaction_level, dtype: float64

uppgift_14

In [30]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, r2_score
from sklearn.ensemble import VotingRegressor, RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor

In [31]:
data = load_diabetes()
print(data.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.
(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)

In [32]:
X, y = load_diabetes(return_X_y=True, as_frame=True)
print(X.info())
print(y.info())

<class 'pandas.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB
None
<class 'pandas.Series'>
RangeIndex: 442 entries, 0 to 441
Series name: target
Non-Null Count  Dtype
--------------  -----
442 non-null    float64
dtypes: float64(1)
memory usage: 3.6 KB
None

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

linjär regression model

In [34]:
model_linreg = LinearRegression()
model_linreg.fit(X_train, y_train)

model_linreg_pred = model_linreg.predict(X_test)
linreg_rmse = root_mean_squared_error(model_linreg_pred, y_test)
print(f"linjär regression rmse: {linreg_rmse}")

linjär regression rmse: 53.85344583676592

In [35]:
r2 = r2_score(y_test, model_linreg_pred)
print(f"r2 score linreg: {r2}")

r2 score linreg: 0.4526027629719197

ensambel modell

In [36]:
linreg = LinearRegression()
tree = DecisionTreeRegressor(
    max_depth=5,           
    min_samples_split=10,
    random_state=42
)
forest = RandomForestRegressor(
    n_estimators=100,
    max_depth=10,         
    min_samples_split=10,
    random_state=42
)

voting_reg = VotingRegressor([('lr', linreg), ('tree', tree), ('forset', forest)])

voting_reg.fit(X_train, y_train)
voting_reg_pred = voting_reg.predict(X_test)
voting_reg_rmse = root_mean_squared_error(voting_reg_pred, y_test)
print(f"voting_reg_rmse: {voting_reg_rmse}")

voting_reg_rmse: 52.88958097035393

In [37]:
r2_voting = r2_score(y_test, voting_reg_pred)
print(f"r2_voting: {r2_voting}")

r2_voting: 0.47202196011036734

uppgift_15

In [38]:
cars = pd.read_csv('car_price_dataset.csv', sep=";")

## EDA

In [39]:
cars.head(10)

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
0,Kia,Rio,2020,4.2,Diesel,Manual,289944,3,5,8501
1,Chevrolet,Malibu,2012,2.0,Hybrid,Automatic,5356,2,3,12092
2,Mercedes,GLA,2020,4.2,Diesel,Automatic,231440,4,2,11171
3,Audi,Q5,2023,2.0,Electric,Manual,160971,2,1,11780
4,Volkswagen,Golf,2003,2.6,Hybrid,Semi-Automatic,286618,3,3,2867
5,Toyota,Camry,2007,2.7,Petrol,Automatic,157889,4,4,7242
6,Honda,Civic,2010,3.4,Electric,Automatic,139584,3,1,11208
7,Kia,Sportage,2001,4.7,Electric,Semi-Automatic,157495,2,2,7950
8,Kia,Sportage,2014,2.6,Hybrid,Manual,98700,3,4,9926
9,Toyota,RAV4,2005,3.1,Petrol,Manual,107724,2,5,6545

In [40]:
cars.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         10000 non-null  str
 1   Model         10000 non-null  str
 2   Year          10000 non-null  int64
 3   Engine_Size   10000 non-null  float64
 4   Fuel_Type     10000 non-null  str
 5   Transmission  10000 non-null  str
 6   Mileage       10000 non-null  int64
 7   Doors         10000 non-null  int64
 8   Owner_Count   10000 non-null  int64
 9   Price         10000 non-null  int64
dtypes: float64(1), int64(5), str(4)
memory usage: 781.4 KB

In [41]:
cars.duplicated().sum()

np.int64(0)

In [42]:
cars.Brand.value_counts()

Brand
Ford          1048
Audi          1038
Volkswagen    1020
Honda         1009
Chevrolet     1003
BMW            999
Hyundai        995
Kia            976
Toyota         970
Mercedes       942
Name: count, dtype: int64

In [43]:
cars = cars.drop(columns='Model')

In [44]:
# tar bort dyra märkes bilar för att modllen ska ha mer konsistent data.
cars_reduced = cars.query("Brand not in ['Mercedes', 'BMW', 'Chevrolet', 'Audi']")

In [45]:
cars_reduced.Brand.value_counts()

Brand
Ford          1048
Volkswagen    1020
Honda         1009
Hyundai        995
Kia            976
Toyota         970
Name: count, dtype: int64

In [46]:
cars_reduced.head(10)

,Brand,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
0,Kia,2020,4.2,Diesel,Manual,289944,3,5,8501
4,Volkswagen,2003,2.6,Hybrid,Semi-Automatic,286618,3,3,2867
5,Toyota,2007,2.7,Petrol,Automatic,157889,4,4,7242
6,Honda,2010,3.4,Electric,Automatic,139584,3,1,11208
7,Kia,2001,4.7,Electric,Semi-Automatic,157495,2,2,7950
8,Kia,2014,2.6,Hybrid,Manual,98700,3,4,9926
9,Toyota,2005,3.1,Petrol,Manual,107724,2,5,6545
11,Volkswagen,2009,4.5,Hybrid,Manual,42795,4,3,11444
12,Honda,2007,4.8,Hybrid,Automatic,132875,3,4,10842
13,Hyundai,2004,2.3,Hybrid,Semi-Automatic,188996,2,1,4820

In [47]:
#df = cars_reduced.sort_values(by=['Brand', 'Price'])
df = cars_reduced[cars_reduced['Brand'] == 'Toyota'].sort_values(by='Price')

In [48]:
df.head(5)

,Brand,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
1538,Toyota,2005,1.4,Diesel,Semi-Automatic,264092,3,1,2000
8216,Toyota,2000,2.7,Diesel,Manual,263062,4,2,2000
1520,Toyota,2000,2.1,Petrol,Semi-Automatic,220704,3,4,2000
2239,Toyota,2005,1.7,Diesel,Semi-Automatic,289249,2,2,2000
3995,Toyota,2000,1.4,Diesel,Semi-Automatic,192625,3,5,2000

In [49]:
cars_reduced_encoded = pd.get_dummies(cars_reduced, columns=['Transmission' , 'Fuel_Type', 'Brand'], drop_first=True)

## Imports

In [50]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
import joblib

## Data split

In [51]:
X = cars_reduced_encoded.drop(columns='Price')
y = cars_reduced_encoded[['Price']]

In [52]:
X.info()

<class 'pandas.DataFrame'>
Index: 6018 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         6018 non-null   int64
 1   Engine_Size                  6018 non-null   float64
 2   Mileage                      6018 non-null   int64
 3   Doors                        6018 non-null   int64
 4   Owner_Count                  6018 non-null   int64
 5   Transmission_Manual          6018 non-null   bool
 6   Transmission_Semi-Automatic  6018 non-null   bool
 7   Fuel_Type_Electric           6018 non-null   bool
 8   Fuel_Type_Hybrid             6018 non-null   bool
 9   Fuel_Type_Petrol             6018 non-null   bool
 10  Brand_Honda                  6018 non-null   bool
 11  Brand_Hyundai                6018 non-null   bool
 12  Brand_Kia                    6018 non-null   bool
 13  Brand_Toyota                 6018 non-null   bool
 14  Brand_Volkswagen             6018 non-null   bool
dtypes: bool(10), float64(1), int64(4)
memory usage: 340.9 KB

In [53]:
X.head()

,Year,Engine_Size,Mileage,Doors,Owner_Count,Transmission_Manual,Transmission_Semi-Automatic,Fuel_Type_Electric,Fuel_Type_Hybrid,Fuel_Type_Petrol,Brand_Honda,Brand_Hyundai,Brand_Kia,Brand_Toyota,Brand_Volkswagen
0,2020,4.2,289944,3,5,True,False,False,False,False,False,False,True,False,False
4,2003,2.6,286618,3,3,False,True,False,True,False,False,False,False,False,True
5,2007,2.7,157889,4,4,False,False,False,False,True,False,False,False,True,False
6,2010,3.4,139584,3,1,False,False,True,False,False,True,False,False,False,False
7,2001,4.7,157495,2,2,False,True,True,False,False,False,False,True,False,False

In [54]:
y.head()

   Price
0   8501
4   2867
5   7242
6  11208
7   7950

In [55]:
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size= 0.20, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size= 0.25, random_state=42)

In [56]:
model_linreg = LinearRegression()
model_linreg.fit(X_train, y_train)

model_linreg_pred = model_linreg.predict(X_val)
linreg_rmse = root_mean_squared_error(model_linreg_pred, y_val)
print(f"linreg rmse: {linreg_rmse}")

linreg rmse: 122.54455516658767

In [57]:
r2 = r2_score(y_val, model_linreg_pred)
print(f"r2 score: {r2}")

r2 score: 0.9984354390998236

## Train the model on full data

In [58]:
model_linreg.fit(X_train_full, y_train_full)

model_linreg_pred_full = model_linreg.predict(X_test)
linreg_rmse_full = root_mean_squared_error(model_linreg_pred_full, y_test)
print(f"linreg rmse full: {linreg_rmse_full}")

linreg rmse full: 56.13412745944358

In [59]:
r2_full = r2_score(y_test, model_linreg_pred_full)
print(f"r2 full score: {r2_full}")

r2 full score: 0.9996734806476262

In [60]:
joblib.dump(model_linreg, 'linreg_model.joblib')

['linreg_model.joblib']

uppgift_16

In [61]:
df = pd.read_csv('diamonds.csv')

## EDA

In [62]:
df.head(10)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
5,6,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48
6,7,0.24,Very Good,I,VVS1,62.3,57.0,336,3.95,3.98,2.47
7,8,0.26,Very Good,H,SI1,61.9,55.0,337,4.07,4.11,2.53
8,9,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49
9,10,0.23,Very Good,H,VS1,59.4,61.0,338,4.00,4.05,2.39

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  53940 non-null  int64
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  str
 3   color       53940 non-null  str
 4   clarity     53940 non-null  str
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(6), int64(2), str(3)
memory usage: 4.5 MB

In [64]:
df = df.drop(columns='Unnamed: 0')

In [65]:
df.cut.value_counts()

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [66]:
df.clarity.value_counts()

clarity
SI1     13065
VS2     12258
SI2      9194
VS1      8171
VVS2     5066
VVS1     3655
IF       1790
I1        741
Name: count, dtype: int64

In [67]:
df.head(10)

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [68]:
cut_order = ['Fair', 'Good', 'Very Good', 'Premium', 'Ideal']
color_order = ['J', 'I', 'H', 'G', 'F', 'E', 'D'] 
clarity_order = ['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF']

In [69]:
df['cut_encoded'] = pd.Categorical(df['cut'], categories=cut_order, ordered=True).codes
df['color_encoded'] = pd.Categorical(df['color'], categories=color_order, ordered=True).codes
df['clarity_encoded'] = pd.Categorical(df['clarity'], categories=clarity_order, ordered=True).codes

In [70]:
df.head()

,carat,cut,color,clarity,depth,table,price,x,y,z,cut_encoded,color_encoded,clarity_encoded
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,4,5,1
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,3,5,2
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,1,5,4
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,3,1,3
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,1,0,1

Data split

In [71]:
features = ['carat','depth','table','x','y','z','cut_encoded','color_encoded','clarity_encoded']

X = df[features]
y = df['price']

In [72]:
X.head()

,carat,depth,table,x,y,z,cut_encoded,color_encoded,clarity_encoded
0,0.23,61.5,55.0,3.95,3.98,2.43,4,5,1
1,0.21,59.8,61.0,3.89,3.84,2.31,3,5,2
2,0.23,56.9,65.0,4.05,4.07,2.31,1,5,4
3,0.29,62.4,58.0,4.20,4.23,2.63,3,1,3
4,0.31,63.3,58.0,4.34,4.35,2.75,1,0,1

In [73]:
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.25, random_state=42)

In [74]:
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

linear_model_pred = linear_model.predict(X_val)
linear_rmse = root_mean_squared_error(linear_model_pred, y_val)
print(f"linear rmse: {linear_rmse}")

linear_r2 = r2_score(y_val, linear_model_pred)
print(f"linear r2 score: {linear_r2}")

linear rmse: 1186.2934211662778
linear r2 score: 0.9097493254240665

In [75]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [76]:
forest = RandomForestRegressor(random_state=42)
forest_hyperparams = { 
'n_estimators':[ 100],
'max_depth':[None,1,5,13,20],
'min_samples_leaf':[2],
}

forest_cv = RandomizedSearchCV(
    forest,
    forest_hyperparams,
    cv = 5,
    scoring='neg_root_mean_squared_error',
    n_jobs=-1
)

forest_cv.fit(X_train, y_train)

c:\Users\amir_\repos\antonio\ai-python-hai25ha\.venv\Lib\site-packages\sklearn\model_selection\_search.py:326: UserWarning: The total space of parameters 5 is smaller than n_iter=10. Running 5 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42),
                   n_jobs=-1,
                   param_distributions={'max_depth': [None, 1, 5, 13, 20],
                                        'min_samples_leaf': [2],
                                        'n_estimators': [100]},
                   scoring='neg_root_mean_squared_error')

In [77]:
rmse = -forest_cv.best_score_
print(f"forest rmse: {rmse}")

forest rmse: 556.3374365416236

In [78]:
forest_cv_pred = forest_cv.predict(X_test)

forest_r2 = r2_score(y_test, forest_cv_pred)
print(f"forest r2 score: {forest_r2}")

forest r2 score: 0.9809081003009872

In [79]:
print(forest_cv.best_params_)


best_model = forest_cv.best_estimator_

{'n_estimators': 100, 'min_samples_leaf': 2, 'max_depth': None}

In [80]:
importance_df = pd.DataFrame({
    "feature": X_train.columns,   # om X_train är en DataFrame
    "importance": best_model.feature_importances_
}).sort_values("importance", ascending=False)

In [81]:

print(importance_df)

           feature  importance
0            carat    0.643838
4                y    0.244770
8  clarity_encoded    0.063547
7    color_encoded    0.031469
5                z    0.005236
3                x    0.004849
1            depth    0.002705
2            table    0.001931
6      cut_encoded    0.001655